#!/usr/bin/python3
# EASY-INSTALL-DEV-SCRIPT: 'eufs-tracks==2.0.0','eufs_tracks_generator'
__requires__ = 'eufs-tracks==2.0.0'
__import__('pkg_resources').require('eufs-tracks==2.0.0')
__file__ = '/home/andrewwhong/classes/16833/iSAM2_SLAM/eufs/build/eufs_tracks/scripts/eufs_tracks_generator'
with open(__file__) as f:
    exec(compile(f.read(), __file__, 'exec'))
