#!/usr/bin/python3
# EASY-INSTALL-DEV-SCRIPT: 'eufs-launcher==2.0.0','eufs_launcher'
__requires__ = 'eufs-launcher==2.0.0'
__import__('pkg_resources').require('eufs-launcher==2.0.0')
__file__ = '/home/andrewwhong/classes/16833/iSAM2_SLAM/eufs/build/eufs_launcher/scripts/eufs_launcher'
with open(__file__) as f:
    exec(compile(f.read(), __file__, 'exec'))
