slam_node:
  ros__parameters:
    use_yaml: true
    # Prior noise model (based on the IMU)
    yaml_prior_imu_x_std_dev: 0.22
    yaml_prior_imu_y_std_dev: 0.22
    yaml_prior_imu_heading_std_dev: 0.00015707963 # radians

    # Bearing range noise model
    yaml_bearing_std_dev: 0.00045
    yaml_range_std_dev: 0.03
    
    # IMU noise model
    yaml_imu_x_std_dev: 0.22
    yaml_imu_y_std_dev: 0.22
    yaml_imu_heading_std_dev: 0.00015707963 # radians

    # GPS noise model
    yaml_gps_x_std_dev: 0.01
    yaml_gps_y_std_dev: 0.01

    # Parameters for performing SLAM cone updates
    yaml_look_radius: 20 # how many surrounding cones to update
    yaml_min_cones_update_all: 50 # update all cone estimates until this number of cones for both blue and yellow
    yaml_window_update: 0 # sliding window cone update 

    # Hardware offsets for IMU and LIDAR
    yaml_imu_offset : 0.0 
    yaml_lidar_offset: 1.0

    # Parameters for limiting what cones we consider for update 
    yaml_max_cone_range: 15.0
    yaml_turning_max_cone_range: 15.0
    yaml_dist_from_start_loop_closure_th: 5.0

    # Mahalanobis distance thresholds for cone updates
    yaml_m_dist_th: 0.1
    yaml_turning_m_dist_th: 0.1
    yaml_update_iterations_n: 5